version: "3"

services:
    db: 
        image: postgres
        restart: always
        environment:
           POSTGRES_PASSWORD: 20wiser20

    server:
        build: 
            context: ./server
            dockerfile: Dockerfile
        container_name: node-container
        command: npm start
        volumes:
            - ./server:/usr/app
        ports:
            - "3333:3333"

    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        command: npm start
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/app
        stdin_open: true