version: "3"

services:
    db: 
        build: ./mysql
        container_name: mysql-container
        command: --default-authentication-plugin=mysql_native_password
        environment: 
            MYSQL_ROOT_PASSWORD: 20wiser20
        volumes: 
            - ./mysql/data:/usr/data
        restart: always

    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        command: npm start
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/app
        stdin_open: true

    server:
        build: 
            context: ./server
            dockerfile: Dockerfile
        command: npm start
        volumes:
            - ./server:/usr/app
        ports:
            - "3333:3333"